### PR TITLE
resolve graphql loaders from single path

### PR DESCRIPTION
**Pull request by jcbbb**
All registered schemes should be able to resolve from same `/query`, but playground types are messed up. You would have to go to `/playground/{name}` to get correct types for testing for now.

### CODE REVIEW

**Comment by diyor28** [comment]
Wow, expected it to be way easier

**Comment by diyor28** [comment]
Please merge main into your branch and reflect the changes that took place since you created the branch

**Comment by jcbbb** [comment]
Like this?

**Comment by diyor28** [comment]
> image
> 
> I have to convert convert these to my own handlers?

Convert them to use the graphql registration approach you introduced

**Comment by jcbbb** [comment]
@diyor28 I only left one graphql controller in core module, which is enough. All other modules should register their schema only.

**Pull request closed without merging**
